# Generated by Django 6.0.5 on 2026-05-25 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRegistro', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=5)),
                ('dataValidade', models.DateField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteiraMotorista', to='locadora.cliente')),
            ],
        ),
    ]
