# Generated by Django 6.0.5 on 2026-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_carteiramotorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('dataNascimento', models.DateField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=60)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataContratacao', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
