# Generated by Django 6.0.5 on 2026-05-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_agencia_funcionario_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('capacidadePassageiros', models.PositiveIntegerField()),
                ('valorAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
