# Generated by Django 6.0.5 on 2026-05-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_categoriaveiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=80)),
                ('ano', models.PositiveIntegerField()),
                ('valorDiaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ipvaPago', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='locadora.agencia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='locadora.categoriaveiculo')),
            ],
        ),
    ]
