# Generated by Django 6.0.4 on 2026-05-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataManutencao', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='EM_ANDAMENTO', max_length=20)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='veiculo.veiculo')),
            ],
        ),
    ]
