# Generated by Django 6.0.4 on 2026-05-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('dataInfracao', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='reserva.reserva')),
            ],
        ),
    ]
