# Generated by Django 6.0.4 on 2026-05-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adicional', '0001_initial'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_adicionais', to='adicional.adicional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_adicionais', to='reserva.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'adicional')},
            },
        ),
    ]
