# Generated by Django 6.0.4 on 2026-05-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencia', '0001_initial'),
        ('cliente', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataReserva', models.DateField()),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('valorTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='ATIVA', max_length=20)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='agencia.agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='cliente.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='veiculo.veiculo')),
            ],
        ),
    ]
